 

// BEGIN Doc Code generated by protoc-gen-trinsic. DO NOT EDIT.
// target: C:\work\sdk\dotnet\Tests\filemanagement_service_examples.cs

// createFileManagementService
// }

// fileManagementUploadFile() {
// }

// fileManagementGetFile() {
// }

// fileManagementDeleteFile() {
// }

// fileManagementListFiles() {
// }

// fileManagementGetStorageStats() {
// }

// END Doc Code generated by protoc-gen-trinsic. DO NOT EDIT.