// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: models/PresentationTemplates.proto

package sdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePresentationTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Attributes []*Attribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *CreatePresentationTemplateRequest) Reset() {
	*x = CreatePresentationTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_PresentationTemplates_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePresentationTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePresentationTemplateRequest) ProtoMessage() {}

func (x *CreatePresentationTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_PresentationTemplates_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePresentationTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreatePresentationTemplateRequest) Descriptor() ([]byte, []int) {
	return file_models_PresentationTemplates_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePresentationTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePresentationTemplateRequest) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CreatePresentationTemplateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Attributes []*Attribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *CreatePresentationTemplateResponse) Reset() {
	*x = CreatePresentationTemplateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_PresentationTemplates_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePresentationTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePresentationTemplateResponse) ProtoMessage() {}

func (x *CreatePresentationTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_PresentationTemplates_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePresentationTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreatePresentationTemplateResponse) Descriptor() ([]byte, []int) {
	return file_models_PresentationTemplates_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePresentationTemplateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePresentationTemplateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePresentationTemplateResponse) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ListPresentationTemplateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Templates []*PresentationTemplate `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
}

func (x *ListPresentationTemplateResponse) Reset() {
	*x = ListPresentationTemplateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_PresentationTemplates_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPresentationTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPresentationTemplateResponse) ProtoMessage() {}

func (x *ListPresentationTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_PresentationTemplates_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPresentationTemplateResponse.ProtoReflect.Descriptor instead.
func (*ListPresentationTemplateResponse) Descriptor() ([]byte, []int) {
	return file_models_PresentationTemplates_proto_rawDescGZIP(), []int{2}
}

func (x *ListPresentationTemplateResponse) GetTemplates() []*PresentationTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type ListPresentationTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPresentationTemplateRequest) Reset() {
	*x = ListPresentationTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_PresentationTemplates_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPresentationTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPresentationTemplateRequest) ProtoMessage() {}

func (x *ListPresentationTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_PresentationTemplates_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPresentationTemplateRequest.ProtoReflect.Descriptor instead.
func (*ListPresentationTemplateRequest) Descriptor() ([]byte, []int) {
	return file_models_PresentationTemplates_proto_rawDescGZIP(), []int{3}
}

type PresentationTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Attributes []*Attribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *PresentationTemplate) Reset() {
	*x = PresentationTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_PresentationTemplates_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresentationTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentationTemplate) ProtoMessage() {}

func (x *PresentationTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_models_PresentationTemplates_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentationTemplate.ProtoReflect.Descriptor instead.
func (*PresentationTemplate) Descriptor() ([]byte, []int) {
	return file_models_PresentationTemplates_proto_rawDescGZIP(), []int{4}
}

func (x *PresentationTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PresentationTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PresentationTemplate) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_models_PresentationTemplates_proto protoreflect.FileDescriptor

var file_models_PresentationTemplates_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x72, 0x69, 0x6e, 0x73, 0x69, 0x63, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x17, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x74, 0x0a, 0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74,
	0x72, 0x69, 0x6e, 0x73, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x22, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x3b, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x72, 0x69, 0x6e, 0x73, 0x69, 0x63, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0x68, 0x0a,
	0x20, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x44, 0x0a, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x74, 0x72, 0x69, 0x6e, 0x73, 0x69, 0x63, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x09, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x22, 0x21, 0x0a, 0x1f, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x77, 0x0a, 0x14, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x72, 0x69,
	0x6e, 0x73, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x72, 0x69, 0x6e, 0x73, 0x69, 0x63, 0x2d, 0x69, 0x64, 0x2f, 0x73, 0x64, 0x6b,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_PresentationTemplates_proto_rawDescOnce sync.Once
	file_models_PresentationTemplates_proto_rawDescData = file_models_PresentationTemplates_proto_rawDesc
)

func file_models_PresentationTemplates_proto_rawDescGZIP() []byte {
	file_models_PresentationTemplates_proto_rawDescOnce.Do(func() {
		file_models_PresentationTemplates_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_PresentationTemplates_proto_rawDescData)
	})
	return file_models_PresentationTemplates_proto_rawDescData
}

var file_models_PresentationTemplates_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_models_PresentationTemplates_proto_goTypes = []interface{}{
	(*CreatePresentationTemplateRequest)(nil),  // 0: trinsic.services.CreatePresentationTemplateRequest
	(*CreatePresentationTemplateResponse)(nil), // 1: trinsic.services.CreatePresentationTemplateResponse
	(*ListPresentationTemplateResponse)(nil),   // 2: trinsic.services.ListPresentationTemplateResponse
	(*ListPresentationTemplateRequest)(nil),    // 3: trinsic.services.ListPresentationTemplateRequest
	(*PresentationTemplate)(nil),               // 4: trinsic.services.PresentationTemplate
	(*Attribute)(nil),                          // 5: trinsic.services.Attribute
}
var file_models_PresentationTemplates_proto_depIdxs = []int32{
	5, // 0: trinsic.services.CreatePresentationTemplateRequest.attributes:type_name -> trinsic.services.Attribute
	5, // 1: trinsic.services.CreatePresentationTemplateResponse.attributes:type_name -> trinsic.services.Attribute
	4, // 2: trinsic.services.ListPresentationTemplateResponse.templates:type_name -> trinsic.services.PresentationTemplate
	5, // 3: trinsic.services.PresentationTemplate.attributes:type_name -> trinsic.services.Attribute
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_models_PresentationTemplates_proto_init() }
func file_models_PresentationTemplates_proto_init() {
	if File_models_PresentationTemplates_proto != nil {
		return
	}
	file_models_Attributes_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_models_PresentationTemplates_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePresentationTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_PresentationTemplates_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePresentationTemplateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_PresentationTemplates_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPresentationTemplateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_PresentationTemplates_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPresentationTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_PresentationTemplates_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresentationTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_PresentationTemplates_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_PresentationTemplates_proto_goTypes,
		DependencyIndexes: file_models_PresentationTemplates_proto_depIdxs,
		MessageInfos:      file_models_PresentationTemplates_proto_msgTypes,
	}.Build()
	File_models_PresentationTemplates_proto = out.File
	file_models_PresentationTemplates_proto_rawDesc = nil
	file_models_PresentationTemplates_proto_goTypes = nil
	file_models_PresentationTemplates_proto_depIdxs = nil
}
