source "https://rubygems.org"

# Specify your gem's dependencies in trinsic.gemspec
gemspec

group :test do
  gem "minitest", "~> 5.0", require: false
end
source "https://rubygems.pkg.github.com/trinsic-id" do
  gem "okapi", ">= 0.1.3"
end