source "https://rubygems.org"

# Specify your gem's dependencies in trinsic.gemspec
gemspec

gem "rake", "~> 12.0"
gem "minitest", "~> 5.0"
gem "google-protobuf"
gem "grpc"
source "https://rubygems.pkg.github.com/trinsic-id" do
  gem "okapi", ">= 0.1.2"
end