source "https://rubygems.org"
gemspec

group :test do
  gem "simplecov", require: false
  gem "simplecov-cobertura", require: false
  gem "minitest", "~> 5.0", require: false
end

source "https://rubygems.pkg.github.com/trinsic-id" do
  gem "okapi", ">= 0.1.3"
end