/*
 * Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Xunit;

namespace Org.OpenAPITools.Test.Model;

/// <summary>
///  Class for testing Session
/// </summary>
/// <remarks>
/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
/// Please update the test case below to test the model.
/// </remarks>
public class SessionTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for Session
    //private Session instance;

    public SessionTests()
    {
        // TODO uncomment below to create an instance of Session
        //instance = new Session();
    }

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of Session
    /// </summary>
    [Fact]
    public void SessionInstanceTest()
    {
        // TODO uncomment below to test "IsType" Session
        //Assert.IsType<Session>(instance);
    }

    /// <summary>
    /// Test the property 'Id'
    /// </summary>
    [Fact]
    public void IdTest()
    {
        // TODO unit test for the property 'Id'
    }

    /// <summary>
    /// Test the property 'ClientToken'
    /// </summary>
    [Fact]
    public void ClientTokenTest()
    {
        // TODO unit test for the property 'ClientToken'
    }

    /// <summary>
    /// Test the property 'State'
    /// </summary>
    [Fact]
    public void StateTest()
    {
        // TODO unit test for the property 'State'
    }

    /// <summary>
    /// Test the property 'Verifications'
    /// </summary>
    [Fact]
    public void VerificationsTest()
    {
        // TODO unit test for the property 'Verifications'
    }

    /// <summary>
    /// Test the property 'FailCode'
    /// </summary>
    [Fact]
    public void FailCodeTest()
    {
        // TODO unit test for the property 'FailCode'
    }

    /// <summary>
    /// Test the property 'ResultVp'
    /// </summary>
    [Fact]
    public void ResultVpTest()
    {
        // TODO unit test for the property 'ResultVp'
    }

    /// <summary>
    /// Test the property 'Created'
    /// </summary>
    [Fact]
    public void CreatedTest()
    {
        // TODO unit test for the property 'Created'
    }

    /// <summary>
    /// Test the property 'Updated'
    /// </summary>
    [Fact]
    public void UpdatedTest()
    {
        // TODO unit test for the property 'Updated'
    }
}
