// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: services/trust-registry/v1/trust-registry.proto

package trustregistry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationStatus int32

const (
	RegistrationStatus_CURRENT    RegistrationStatus = 0 // - the entity is currently authorized, as of time of the query.
	RegistrationStatus_EXPIRED    RegistrationStatus = 1 // - entity rights have expired.
	RegistrationStatus_TERMINATED RegistrationStatus = 2 // - entity has voluntarily ceased Issuer role under the specific EGF.
	RegistrationStatus_REVOKED    RegistrationStatus = 3 // - entity authority under specific EGF was terminated by the governing authority.
	RegistrationStatus_NOT_FOUND  RegistrationStatus = 10
)

// Enum value maps for RegistrationStatus.
var (
	RegistrationStatus_name = map[int32]string{
		0:  "CURRENT",
		1:  "EXPIRED",
		2:  "TERMINATED",
		3:  "REVOKED",
		10: "NOT_FOUND",
	}
	RegistrationStatus_value = map[string]int32{
		"CURRENT":    0,
		"EXPIRED":    1,
		"TERMINATED": 2,
		"REVOKED":    3,
		"NOT_FOUND":  10,
	}
)

func (x RegistrationStatus) Enum() *RegistrationStatus {
	p := new(RegistrationStatus)
	*p = x
	return p
}

func (x RegistrationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_services_trust_registry_v1_trust_registry_proto_enumTypes[0].Descriptor()
}

func (RegistrationStatus) Type() protoreflect.EnumType {
	return &file_services_trust_registry_v1_trust_registry_proto_enumTypes[0]
}

func (x RegistrationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrationStatus.Descriptor instead.
func (RegistrationStatus) EnumDescriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{0}
}

// Register new ecosystem governance framework
type AddFrameworkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GovernanceFrameworkUri string `protobuf:"bytes,1,opt,name=governance_framework_uri,json=governanceFrameworkUri,proto3" json:"governance_framework_uri,omitempty"`
	Name                   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description            string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *AddFrameworkRequest) Reset() {
	*x = AddFrameworkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFrameworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFrameworkRequest) ProtoMessage() {}

func (x *AddFrameworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFrameworkRequest.ProtoReflect.Descriptor instead.
func (*AddFrameworkRequest) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{0}
}

func (x *AddFrameworkRequest) GetGovernanceFrameworkUri() string {
	if x != nil {
		return x.GovernanceFrameworkUri
	}
	return ""
}

func (x *AddFrameworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddFrameworkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddFrameworkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique framework identifier
	Id                 string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GoverningAuthority string `protobuf:"bytes,2,opt,name=governing_authority,json=governingAuthority,proto3" json:"governing_authority,omitempty"`
	TrustRegistry      string `protobuf:"bytes,3,opt,name=trust_registry,json=trustRegistry,proto3" json:"trust_registry,omitempty"`
}

func (x *AddFrameworkResponse) Reset() {
	*x = AddFrameworkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFrameworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFrameworkResponse) ProtoMessage() {}

func (x *AddFrameworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFrameworkResponse.ProtoReflect.Descriptor instead.
func (*AddFrameworkResponse) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{1}
}

func (x *AddFrameworkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddFrameworkResponse) GetGoverningAuthority() string {
	if x != nil {
		return x.GoverningAuthority
	}
	return ""
}

func (x *AddFrameworkResponse) GetTrustRegistry() string {
	if x != nil {
		return x.TrustRegistry
	}
	return ""
}

type RemoveFrameworkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveFrameworkRequest) Reset() {
	*x = RemoveFrameworkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFrameworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFrameworkRequest) ProtoMessage() {}

func (x *RemoveFrameworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFrameworkRequest.ProtoReflect.Descriptor instead.
func (*RemoveFrameworkRequest) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveFrameworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveFrameworkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveFrameworkResponse) Reset() {
	*x = RemoveFrameworkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFrameworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFrameworkResponse) ProtoMessage() {}

func (x *RemoveFrameworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFrameworkResponse.ProtoReflect.Descriptor instead.
func (*RemoveFrameworkResponse) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{3}
}

type SearchRegistryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query             string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // SELECT c from c where c.type == 'GovernanceFramework'
	ContinuationToken string `protobuf:"bytes,2,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
}

func (x *SearchRegistryRequest) Reset() {
	*x = SearchRegistryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRegistryRequest) ProtoMessage() {}

func (x *SearchRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRegistryRequest.ProtoReflect.Descriptor instead.
func (*SearchRegistryRequest) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{4}
}

func (x *SearchRegistryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRegistryRequest) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

type SearchRegistryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemsJson         string `protobuf:"bytes,1,opt,name=items_json,json=itemsJson,proto3" json:"items_json,omitempty"`
	HasMore           bool   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	ContinuationToken string `protobuf:"bytes,4,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
}

func (x *SearchRegistryResponse) Reset() {
	*x = SearchRegistryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRegistryResponse) ProtoMessage() {}

func (x *SearchRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRegistryResponse.ProtoReflect.Descriptor instead.
func (*SearchRegistryResponse) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{5}
}

func (x *SearchRegistryResponse) GetItemsJson() string {
	if x != nil {
		return x.ItemsJson
	}
	return ""
}

func (x *SearchRegistryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SearchRegistryResponse) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

type GovernanceFramework struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GovernanceFrameworkUri string `protobuf:"bytes,1,opt,name=governance_framework_uri,json=governanceFrameworkUri,proto3" json:"governance_framework_uri,omitempty"`
	TrustRegistryUri       string `protobuf:"bytes,2,opt,name=trust_registry_uri,json=trustRegistryUri,proto3" json:"trust_registry_uri,omitempty"`
	Description            string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *GovernanceFramework) Reset() {
	*x = GovernanceFramework{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GovernanceFramework) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernanceFramework) ProtoMessage() {}

func (x *GovernanceFramework) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernanceFramework.ProtoReflect.Descriptor instead.
func (*GovernanceFramework) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{6}
}

func (x *GovernanceFramework) GetGovernanceFrameworkUri() string {
	if x != nil {
		return x.GovernanceFrameworkUri
	}
	return ""
}

func (x *GovernanceFramework) GetTrustRegistryUri() string {
	if x != nil {
		return x.TrustRegistryUri
	}
	return ""
}

func (x *GovernanceFramework) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RegisterMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Member:
	//	*RegisterMemberRequest_DidUri
	//	*RegisterMemberRequest_WalletId
	//	*RegisterMemberRequest_Email
	Member        isRegisterMemberRequest_Member `protobuf_oneof:"member"`
	SchemaUri     string                         `protobuf:"bytes,10,opt,name=schema_uri,json=schemaUri,proto3" json:"schema_uri,omitempty"`
	ValidFromUtc  uint64                         `protobuf:"varint,11,opt,name=valid_from_utc,json=validFromUtc,proto3" json:"valid_from_utc,omitempty"`
	ValidUntilUtc uint64                         `protobuf:"varint,12,opt,name=valid_until_utc,json=validUntilUtc,proto3" json:"valid_until_utc,omitempty"`
	// the id of the governance framework
	FrameworkId string `protobuf:"bytes,30,opt,name=framework_id,json=frameworkId,proto3" json:"framework_id,omitempty"`
}

func (x *RegisterMemberRequest) Reset() {
	*x = RegisterMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMemberRequest) ProtoMessage() {}

func (x *RegisterMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMemberRequest.ProtoReflect.Descriptor instead.
func (*RegisterMemberRequest) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{7}
}

func (m *RegisterMemberRequest) GetMember() isRegisterMemberRequest_Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (x *RegisterMemberRequest) GetDidUri() string {
	if x, ok := x.GetMember().(*RegisterMemberRequest_DidUri); ok {
		return x.DidUri
	}
	return ""
}

func (x *RegisterMemberRequest) GetWalletId() string {
	if x, ok := x.GetMember().(*RegisterMemberRequest_WalletId); ok {
		return x.WalletId
	}
	return ""
}

func (x *RegisterMemberRequest) GetEmail() string {
	if x, ok := x.GetMember().(*RegisterMemberRequest_Email); ok {
		return x.Email
	}
	return ""
}

func (x *RegisterMemberRequest) GetSchemaUri() string {
	if x != nil {
		return x.SchemaUri
	}
	return ""
}

func (x *RegisterMemberRequest) GetValidFromUtc() uint64 {
	if x != nil {
		return x.ValidFromUtc
	}
	return 0
}

func (x *RegisterMemberRequest) GetValidUntilUtc() uint64 {
	if x != nil {
		return x.ValidUntilUtc
	}
	return 0
}

func (x *RegisterMemberRequest) GetFrameworkId() string {
	if x != nil {
		return x.FrameworkId
	}
	return ""
}

type isRegisterMemberRequest_Member interface {
	isRegisterMemberRequest_Member()
}

type RegisterMemberRequest_DidUri struct {
	DidUri string `protobuf:"bytes,1,opt,name=did_uri,json=didUri,proto3,oneof"`
}

type RegisterMemberRequest_WalletId struct {
	WalletId string `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3,oneof"`
}

type RegisterMemberRequest_Email struct {
	Email string `protobuf:"bytes,4,opt,name=email,proto3,oneof"`
}

func (*RegisterMemberRequest_DidUri) isRegisterMemberRequest_Member() {}

func (*RegisterMemberRequest_WalletId) isRegisterMemberRequest_Member() {}

func (*RegisterMemberRequest_Email) isRegisterMemberRequest_Member() {}

type RegisterMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterMemberResponse) Reset() {
	*x = RegisterMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMemberResponse) ProtoMessage() {}

func (x *RegisterMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMemberResponse.ProtoReflect.Descriptor instead.
func (*RegisterMemberResponse) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{8}
}

type UnregisterMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Member:
	//	*UnregisterMemberRequest_DidUri
	//	*UnregisterMemberRequest_WalletId
	//	*UnregisterMemberRequest_Email
	Member      isUnregisterMemberRequest_Member `protobuf_oneof:"member"`
	SchemaUri   string                           `protobuf:"bytes,10,opt,name=schema_uri,json=schemaUri,proto3" json:"schema_uri,omitempty"`
	FrameworkId string                           `protobuf:"bytes,20,opt,name=framework_id,json=frameworkId,proto3" json:"framework_id,omitempty"`
}

func (x *UnregisterMemberRequest) Reset() {
	*x = UnregisterMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnregisterMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterMemberRequest) ProtoMessage() {}

func (x *UnregisterMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterMemberRequest.ProtoReflect.Descriptor instead.
func (*UnregisterMemberRequest) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{9}
}

func (m *UnregisterMemberRequest) GetMember() isUnregisterMemberRequest_Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (x *UnregisterMemberRequest) GetDidUri() string {
	if x, ok := x.GetMember().(*UnregisterMemberRequest_DidUri); ok {
		return x.DidUri
	}
	return ""
}

func (x *UnregisterMemberRequest) GetWalletId() string {
	if x, ok := x.GetMember().(*UnregisterMemberRequest_WalletId); ok {
		return x.WalletId
	}
	return ""
}

func (x *UnregisterMemberRequest) GetEmail() string {
	if x, ok := x.GetMember().(*UnregisterMemberRequest_Email); ok {
		return x.Email
	}
	return ""
}

func (x *UnregisterMemberRequest) GetSchemaUri() string {
	if x != nil {
		return x.SchemaUri
	}
	return ""
}

func (x *UnregisterMemberRequest) GetFrameworkId() string {
	if x != nil {
		return x.FrameworkId
	}
	return ""
}

type isUnregisterMemberRequest_Member interface {
	isUnregisterMemberRequest_Member()
}

type UnregisterMemberRequest_DidUri struct {
	DidUri string `protobuf:"bytes,1,opt,name=did_uri,json=didUri,proto3,oneof"`
}

type UnregisterMemberRequest_WalletId struct {
	WalletId string `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3,oneof"`
}

type UnregisterMemberRequest_Email struct {
	Email string `protobuf:"bytes,4,opt,name=email,proto3,oneof"`
}

func (*UnregisterMemberRequest_DidUri) isUnregisterMemberRequest_Member() {}

func (*UnregisterMemberRequest_WalletId) isUnregisterMemberRequest_Member() {}

func (*UnregisterMemberRequest_Email) isUnregisterMemberRequest_Member() {}

type UnregisterMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnregisterMemberResponse) Reset() {
	*x = UnregisterMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnregisterMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterMemberResponse) ProtoMessage() {}

func (x *UnregisterMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterMemberResponse.ProtoReflect.Descriptor instead.
func (*UnregisterMemberResponse) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{10}
}

type GetMembershipStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GovernanceFrameworkUri string `protobuf:"bytes,1,opt,name=governance_framework_uri,json=governanceFrameworkUri,proto3" json:"governance_framework_uri,omitempty"`
	// Types that are assignable to Member:
	//	*GetMembershipStatusRequest_DidUri
	//	*GetMembershipStatusRequest_X509Cert
	Member    isGetMembershipStatusRequest_Member `protobuf_oneof:"member"`
	SchemaUri string                              `protobuf:"bytes,4,opt,name=schema_uri,json=schemaUri,proto3" json:"schema_uri,omitempty"`
}

func (x *GetMembershipStatusRequest) Reset() {
	*x = GetMembershipStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembershipStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipStatusRequest) ProtoMessage() {}

func (x *GetMembershipStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMembershipStatusRequest) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{11}
}

func (x *GetMembershipStatusRequest) GetGovernanceFrameworkUri() string {
	if x != nil {
		return x.GovernanceFrameworkUri
	}
	return ""
}

func (m *GetMembershipStatusRequest) GetMember() isGetMembershipStatusRequest_Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (x *GetMembershipStatusRequest) GetDidUri() string {
	if x, ok := x.GetMember().(*GetMembershipStatusRequest_DidUri); ok {
		return x.DidUri
	}
	return ""
}

func (x *GetMembershipStatusRequest) GetX509Cert() string {
	if x, ok := x.GetMember().(*GetMembershipStatusRequest_X509Cert); ok {
		return x.X509Cert
	}
	return ""
}

func (x *GetMembershipStatusRequest) GetSchemaUri() string {
	if x != nil {
		return x.SchemaUri
	}
	return ""
}

type isGetMembershipStatusRequest_Member interface {
	isGetMembershipStatusRequest_Member()
}

type GetMembershipStatusRequest_DidUri struct {
	DidUri string `protobuf:"bytes,2,opt,name=did_uri,json=didUri,proto3,oneof"`
}

type GetMembershipStatusRequest_X509Cert struct {
	X509Cert string `protobuf:"bytes,3,opt,name=x509_cert,json=x509Cert,proto3,oneof"`
}

func (*GetMembershipStatusRequest_DidUri) isGetMembershipStatusRequest_Member() {}

func (*GetMembershipStatusRequest_X509Cert) isGetMembershipStatusRequest_Member() {}

type GetMembershipStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status RegistrationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=services.trustregistry.v1.RegistrationStatus" json:"status,omitempty"`
}

func (x *GetMembershipStatusResponse) Reset() {
	*x = GetMembershipStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembershipStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipStatusResponse) ProtoMessage() {}

func (x *GetMembershipStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMembershipStatusResponse) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{12}
}

func (x *GetMembershipStatusResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_CURRENT
}

type FetchDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GovernanceFrameworkUri string `protobuf:"bytes,1,opt,name=governance_framework_uri,json=governanceFrameworkUri,proto3" json:"governance_framework_uri,omitempty"`
	Query                  string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *FetchDataRequest) Reset() {
	*x = FetchDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataRequest) ProtoMessage() {}

func (x *FetchDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataRequest.ProtoReflect.Descriptor instead.
func (*FetchDataRequest) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{13}
}

func (x *FetchDataRequest) GetGovernanceFrameworkUri() string {
	if x != nil {
		return x.GovernanceFrameworkUri
	}
	return ""
}

func (x *FetchDataRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type FetchDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseJson      string `protobuf:"bytes,1,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	HasMoreResults    bool   `protobuf:"varint,2,opt,name=has_more_results,json=hasMoreResults,proto3" json:"has_more_results,omitempty"`
	ContinuationToken string `protobuf:"bytes,3,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
}

func (x *FetchDataResponse) Reset() {
	*x = FetchDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataResponse) ProtoMessage() {}

func (x *FetchDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_trust_registry_v1_trust_registry_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataResponse.ProtoReflect.Descriptor instead.
func (*FetchDataResponse) Descriptor() ([]byte, []int) {
	return file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP(), []int{14}
}

func (x *FetchDataResponse) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

func (x *FetchDataResponse) GetHasMoreResults() bool {
	if x != nil {
		return x.HasMoreResults
	}
	return false
}

func (x *FetchDataResponse) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

var File_services_trust_registry_v1_trust_registry_proto protoreflect.FileDescriptor

var file_services_trust_registry_v1_trust_registry_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x2d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x75,
	0x73, 0x74, 0x2d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x19, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73,
	0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x85, 0x01, 0x0a,
	0x13, 0x41, 0x64, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x18, 0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x75, 0x72, 0x69,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x55, 0x72, 0x69, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7e, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x13,
	0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x67, 0x6f, 0x76, 0x65, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x25, 0x0a,
	0x0e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x22, 0x28, 0x0a, 0x16, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19,
	0x0a, 0x17, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5c, 0x0a, 0x15, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x74,
	0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x81, 0x01, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x4a, 0x73, 0x6f,
	0x6e, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6d, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x12, 0x2d, 0x0a, 0x12,
	0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x9f, 0x01, 0x0a, 0x13,
	0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x12, 0x38, 0x0a, 0x18, 0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x75, 0x72, 0x69, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x55, 0x72, 0x69, 0x12, 0x2c, 0x0a,
	0x12, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x5f,
	0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x55, 0x72, 0x69, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x83, 0x02,
	0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x64, 0x69, 0x64, 0x5f, 0x75,
	0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x64, 0x69, 0x64, 0x55,
	0x72, 0x69, 0x12, 0x1d, 0x0a, 0x09, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x55, 0x72, 0x69, 0x12, 0x24, 0x0a, 0x0e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x74, 0x63, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x74, 0x63, 0x12, 0x26,
	0x0a, 0x0f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x5f, 0x75, 0x74,
	0x63, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x55, 0x6e,
	0x74, 0x69, 0x6c, 0x55, 0x74, 0x63, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x18, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xb7, 0x01,
	0x0a, 0x17, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x64, 0x69, 0x64,
	0x5f, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x64, 0x69,
	0x64, 0x55, 0x72, 0x69, 0x12, 0x1d, 0x0a, 0x09, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x55, 0x72, 0x69, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x42, 0x08, 0x0a,
	0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x6e, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0xb9, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x38, 0x0a, 0x18, 0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63, 0x65,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x55, 0x72, 0x69, 0x12, 0x19, 0x0a, 0x07,
	0x64, 0x69, 0x64, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x06, 0x64, 0x69, 0x64, 0x55, 0x72, 0x69, 0x12, 0x1d, 0x0a, 0x09, 0x78, 0x35, 0x30, 0x39, 0x5f,
	0x63, 0x65, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x78, 0x35,
	0x30, 0x39, 0x43, 0x65, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x5f, 0x75, 0x72, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x55, 0x72, 0x69, 0x42, 0x08, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x64, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x62, 0x0a, 0x10, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x18, 0x67, 0x6f, 0x76,
	0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x67, 0x6f, 0x76,
	0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x55, 0x72, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x91, 0x01, 0x0a, 0x11, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x68, 0x61, 0x73, 0x5f, 0x6d, 0x6f, 0x72, 0x65,
	0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e,
	0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x2d,
	0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x74,
	0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2a, 0x5a, 0x0a,
	0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x54, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0e, 0x0a,
	0x0a, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x52, 0x45, 0x56, 0x4f, 0x4b, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f,
	0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x0a, 0x32, 0xd6, 0x06, 0x0a, 0x0d, 0x54, 0x72,
	0x75, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x6f, 0x0a, 0x0c, 0x41,
	0x64, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x2e, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x78, 0x0a, 0x0f,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x12,
	0x31, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x32, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72,
	0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x75, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x30, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x75, 0x0a,
	0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x30, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x31, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75,
	0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7b, 0x0a, 0x10, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x32, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x84, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x35, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x36, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73,
	0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x09, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72,
	0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x30, 0x01, 0x42, 0x72, 0x0a, 0x21, 0x74, 0x72, 0x69, 0x6e, 0x73, 0x69, 0x63, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0xaa, 0x02, 0x21, 0x54, 0x72, 0x69, 0x6e, 0x73, 0x69, 0x63, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x54, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x2e, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_trust_registry_v1_trust_registry_proto_rawDescOnce sync.Once
	file_services_trust_registry_v1_trust_registry_proto_rawDescData = file_services_trust_registry_v1_trust_registry_proto_rawDesc
)

func file_services_trust_registry_v1_trust_registry_proto_rawDescGZIP() []byte {
	file_services_trust_registry_v1_trust_registry_proto_rawDescOnce.Do(func() {
		file_services_trust_registry_v1_trust_registry_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_trust_registry_v1_trust_registry_proto_rawDescData)
	})
	return file_services_trust_registry_v1_trust_registry_proto_rawDescData
}

var file_services_trust_registry_v1_trust_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_trust_registry_v1_trust_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_services_trust_registry_v1_trust_registry_proto_goTypes = []interface{}{
	(RegistrationStatus)(0),             // 0: services.trustregistry.v1.RegistrationStatus
	(*AddFrameworkRequest)(nil),         // 1: services.trustregistry.v1.AddFrameworkRequest
	(*AddFrameworkResponse)(nil),        // 2: services.trustregistry.v1.AddFrameworkResponse
	(*RemoveFrameworkRequest)(nil),      // 3: services.trustregistry.v1.RemoveFrameworkRequest
	(*RemoveFrameworkResponse)(nil),     // 4: services.trustregistry.v1.RemoveFrameworkResponse
	(*SearchRegistryRequest)(nil),       // 5: services.trustregistry.v1.SearchRegistryRequest
	(*SearchRegistryResponse)(nil),      // 6: services.trustregistry.v1.SearchRegistryResponse
	(*GovernanceFramework)(nil),         // 7: services.trustregistry.v1.GovernanceFramework
	(*RegisterMemberRequest)(nil),       // 8: services.trustregistry.v1.RegisterMemberRequest
	(*RegisterMemberResponse)(nil),      // 9: services.trustregistry.v1.RegisterMemberResponse
	(*UnregisterMemberRequest)(nil),     // 10: services.trustregistry.v1.UnregisterMemberRequest
	(*UnregisterMemberResponse)(nil),    // 11: services.trustregistry.v1.UnregisterMemberResponse
	(*GetMembershipStatusRequest)(nil),  // 12: services.trustregistry.v1.GetMembershipStatusRequest
	(*GetMembershipStatusResponse)(nil), // 13: services.trustregistry.v1.GetMembershipStatusResponse
	(*FetchDataRequest)(nil),            // 14: services.trustregistry.v1.FetchDataRequest
	(*FetchDataResponse)(nil),           // 15: services.trustregistry.v1.FetchDataResponse
}
var file_services_trust_registry_v1_trust_registry_proto_depIdxs = []int32{
	0,  // 0: services.trustregistry.v1.GetMembershipStatusResponse.status:type_name -> services.trustregistry.v1.RegistrationStatus
	1,  // 1: services.trustregistry.v1.TrustRegistry.AddFramework:input_type -> services.trustregistry.v1.AddFrameworkRequest
	3,  // 2: services.trustregistry.v1.TrustRegistry.RemoveFramework:input_type -> services.trustregistry.v1.RemoveFrameworkRequest
	5,  // 3: services.trustregistry.v1.TrustRegistry.SearchRegistry:input_type -> services.trustregistry.v1.SearchRegistryRequest
	8,  // 4: services.trustregistry.v1.TrustRegistry.RegisterMember:input_type -> services.trustregistry.v1.RegisterMemberRequest
	10, // 5: services.trustregistry.v1.TrustRegistry.UnregisterMember:input_type -> services.trustregistry.v1.UnregisterMemberRequest
	12, // 6: services.trustregistry.v1.TrustRegistry.GetMembershipStatus:input_type -> services.trustregistry.v1.GetMembershipStatusRequest
	14, // 7: services.trustregistry.v1.TrustRegistry.FetchData:input_type -> services.trustregistry.v1.FetchDataRequest
	2,  // 8: services.trustregistry.v1.TrustRegistry.AddFramework:output_type -> services.trustregistry.v1.AddFrameworkResponse
	4,  // 9: services.trustregistry.v1.TrustRegistry.RemoveFramework:output_type -> services.trustregistry.v1.RemoveFrameworkResponse
	6,  // 10: services.trustregistry.v1.TrustRegistry.SearchRegistry:output_type -> services.trustregistry.v1.SearchRegistryResponse
	9,  // 11: services.trustregistry.v1.TrustRegistry.RegisterMember:output_type -> services.trustregistry.v1.RegisterMemberResponse
	11, // 12: services.trustregistry.v1.TrustRegistry.UnregisterMember:output_type -> services.trustregistry.v1.UnregisterMemberResponse
	13, // 13: services.trustregistry.v1.TrustRegistry.GetMembershipStatus:output_type -> services.trustregistry.v1.GetMembershipStatusResponse
	15, // 14: services.trustregistry.v1.TrustRegistry.FetchData:output_type -> services.trustregistry.v1.FetchDataResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_services_trust_registry_v1_trust_registry_proto_init() }
func file_services_trust_registry_v1_trust_registry_proto_init() {
	if File_services_trust_registry_v1_trust_registry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFrameworkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFrameworkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFrameworkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFrameworkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRegistryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRegistryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GovernanceFramework); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnregisterMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnregisterMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembershipStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembershipStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_trust_registry_v1_trust_registry_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_services_trust_registry_v1_trust_registry_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*RegisterMemberRequest_DidUri)(nil),
		(*RegisterMemberRequest_WalletId)(nil),
		(*RegisterMemberRequest_Email)(nil),
	}
	file_services_trust_registry_v1_trust_registry_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*UnregisterMemberRequest_DidUri)(nil),
		(*UnregisterMemberRequest_WalletId)(nil),
		(*UnregisterMemberRequest_Email)(nil),
	}
	file_services_trust_registry_v1_trust_registry_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*GetMembershipStatusRequest_DidUri)(nil),
		(*GetMembershipStatusRequest_X509Cert)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_trust_registry_v1_trust_registry_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_trust_registry_v1_trust_registry_proto_goTypes,
		DependencyIndexes: file_services_trust_registry_v1_trust_registry_proto_depIdxs,
		EnumInfos:         file_services_trust_registry_v1_trust_registry_proto_enumTypes,
		MessageInfos:      file_services_trust_registry_v1_trust_registry_proto_msgTypes,
	}.Build()
	File_services_trust_registry_v1_trust_registry_proto = out.File
	file_services_trust_registry_v1_trust_registry_proto_rawDesc = nil
	file_services_trust_registry_v1_trust_registry_proto_goTypes = nil
	file_services_trust_registry_v1_trust_registry_proto_depIdxs = nil
}
