// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CoreService.proto

package trinsic.services;

public final class CoreService {
  private CoreService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code trinsic.services.ResponseStatus}
   */
  public enum ResponseStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <code>WALLET_ACCESS_DENIED = 10;</code>
     */
    WALLET_ACCESS_DENIED(10),
    /**
     * <code>WALLET_EXISTS = 11;</code>
     */
    WALLET_EXISTS(11),
    /**
     * <code>ITEM_NOT_FOUND = 20;</code>
     */
    ITEM_NOT_FOUND(20),
    /**
     * <code>SERIALIZATION_ERROR = 200;</code>
     */
    SERIALIZATION_ERROR(200),
    /**
     * <code>UNKNOWN_ERROR = 100;</code>
     */
    UNKNOWN_ERROR(100),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>WALLET_ACCESS_DENIED = 10;</code>
     */
    public static final int WALLET_ACCESS_DENIED_VALUE = 10;
    /**
     * <code>WALLET_EXISTS = 11;</code>
     */
    public static final int WALLET_EXISTS_VALUE = 11;
    /**
     * <code>ITEM_NOT_FOUND = 20;</code>
     */
    public static final int ITEM_NOT_FOUND_VALUE = 20;
    /**
     * <code>SERIALIZATION_ERROR = 200;</code>
     */
    public static final int SERIALIZATION_ERROR_VALUE = 200;
    /**
     * <code>UNKNOWN_ERROR = 100;</code>
     */
    public static final int UNKNOWN_ERROR_VALUE = 100;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ResponseStatus forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 10: return WALLET_ACCESS_DENIED;
        case 11: return WALLET_EXISTS;
        case 20: return ITEM_NOT_FOUND;
        case 200: return SERIALIZATION_ERROR;
        case 100: return UNKNOWN_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseStatus>() {
            public ResponseStatus findValueByNumber(int number) {
              return ResponseStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return trinsic.services.CoreService.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResponseStatus[] VALUES = values();

    public static ResponseStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResponseStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:trinsic.services.ResponseStatus)
  }

  /**
   * Protobuf enum {@code trinsic.services.JsonFormat}
   */
  public enum JsonFormat
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Protobuf = 0;</code>
     */
    Protobuf(0),
    /**
     * <code>Binary = 1;</code>
     */
    Binary(1),
    /**
     * <code>String = 2;</code>
     */
    String(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Protobuf = 0;</code>
     */
    public static final int Protobuf_VALUE = 0;
    /**
     * <code>Binary = 1;</code>
     */
    public static final int Binary_VALUE = 1;
    /**
     * <code>String = 2;</code>
     */
    public static final int String_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static JsonFormat valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static JsonFormat forNumber(int value) {
      switch (value) {
        case 0: return Protobuf;
        case 1: return Binary;
        case 2: return String;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<JsonFormat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        JsonFormat> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<JsonFormat>() {
            public JsonFormat findValueByNumber(int number) {
              return JsonFormat.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return trinsic.services.CoreService.getDescriptor().getEnumTypes().get(1);
    }

    private static final JsonFormat[] VALUES = values();

    public static JsonFormat valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private JsonFormat(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:trinsic.services.JsonFormat)
  }

  public interface RequestOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trinsic.services.RequestOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.trinsic.services.JsonFormat response_json_format = 1;</code>
     * @return The enum numeric value on the wire for responseJsonFormat.
     */
    int getResponseJsonFormatValue();
    /**
     * <code>.trinsic.services.JsonFormat response_json_format = 1;</code>
     * @return The responseJsonFormat.
     */
    trinsic.services.CoreService.JsonFormat getResponseJsonFormat();
  }
  /**
   * Protobuf type {@code trinsic.services.RequestOptions}
   */
  public static final class RequestOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trinsic.services.RequestOptions)
      RequestOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestOptions.newBuilder() to construct.
    private RequestOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestOptions() {
      responseJsonFormat_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestOptions();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              responseJsonFormat_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trinsic.services.CoreService.internal_static_trinsic_services_RequestOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trinsic.services.CoreService.internal_static_trinsic_services_RequestOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trinsic.services.CoreService.RequestOptions.class, trinsic.services.CoreService.RequestOptions.Builder.class);
    }

    public static final int RESPONSE_JSON_FORMAT_FIELD_NUMBER = 1;
    private int responseJsonFormat_;
    /**
     * <code>.trinsic.services.JsonFormat response_json_format = 1;</code>
     * @return The enum numeric value on the wire for responseJsonFormat.
     */
    @java.lang.Override public int getResponseJsonFormatValue() {
      return responseJsonFormat_;
    }
    /**
     * <code>.trinsic.services.JsonFormat response_json_format = 1;</code>
     * @return The responseJsonFormat.
     */
    @java.lang.Override public trinsic.services.CoreService.JsonFormat getResponseJsonFormat() {
      @SuppressWarnings("deprecation")
      trinsic.services.CoreService.JsonFormat result = trinsic.services.CoreService.JsonFormat.valueOf(responseJsonFormat_);
      return result == null ? trinsic.services.CoreService.JsonFormat.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseJsonFormat_ != trinsic.services.CoreService.JsonFormat.Protobuf.getNumber()) {
        output.writeEnum(1, responseJsonFormat_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responseJsonFormat_ != trinsic.services.CoreService.JsonFormat.Protobuf.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, responseJsonFormat_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof trinsic.services.CoreService.RequestOptions)) {
        return super.equals(obj);
      }
      trinsic.services.CoreService.RequestOptions other = (trinsic.services.CoreService.RequestOptions) obj;

      if (responseJsonFormat_ != other.responseJsonFormat_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_JSON_FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + responseJsonFormat_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static trinsic.services.CoreService.RequestOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trinsic.services.CoreService.RequestOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trinsic.services.CoreService.RequestOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trinsic.services.CoreService.RequestOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trinsic.services.CoreService.RequestOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trinsic.services.CoreService.RequestOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trinsic.services.CoreService.RequestOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trinsic.services.CoreService.RequestOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static trinsic.services.CoreService.RequestOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static trinsic.services.CoreService.RequestOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static trinsic.services.CoreService.RequestOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trinsic.services.CoreService.RequestOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(trinsic.services.CoreService.RequestOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trinsic.services.RequestOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trinsic.services.RequestOptions)
        trinsic.services.CoreService.RequestOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return trinsic.services.CoreService.internal_static_trinsic_services_RequestOptions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return trinsic.services.CoreService.internal_static_trinsic_services_RequestOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                trinsic.services.CoreService.RequestOptions.class, trinsic.services.CoreService.RequestOptions.Builder.class);
      }

      // Construct using trinsic.services.CoreService.RequestOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseJsonFormat_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return trinsic.services.CoreService.internal_static_trinsic_services_RequestOptions_descriptor;
      }

      @java.lang.Override
      public trinsic.services.CoreService.RequestOptions getDefaultInstanceForType() {
        return trinsic.services.CoreService.RequestOptions.getDefaultInstance();
      }

      @java.lang.Override
      public trinsic.services.CoreService.RequestOptions build() {
        trinsic.services.CoreService.RequestOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public trinsic.services.CoreService.RequestOptions buildPartial() {
        trinsic.services.CoreService.RequestOptions result = new trinsic.services.CoreService.RequestOptions(this);
        result.responseJsonFormat_ = responseJsonFormat_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof trinsic.services.CoreService.RequestOptions) {
          return mergeFrom((trinsic.services.CoreService.RequestOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(trinsic.services.CoreService.RequestOptions other) {
        if (other == trinsic.services.CoreService.RequestOptions.getDefaultInstance()) return this;
        if (other.responseJsonFormat_ != 0) {
          setResponseJsonFormatValue(other.getResponseJsonFormatValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        trinsic.services.CoreService.RequestOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (trinsic.services.CoreService.RequestOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int responseJsonFormat_ = 0;
      /**
       * <code>.trinsic.services.JsonFormat response_json_format = 1;</code>
       * @return The enum numeric value on the wire for responseJsonFormat.
       */
      @java.lang.Override public int getResponseJsonFormatValue() {
        return responseJsonFormat_;
      }
      /**
       * <code>.trinsic.services.JsonFormat response_json_format = 1;</code>
       * @param value The enum numeric value on the wire for responseJsonFormat to set.
       * @return This builder for chaining.
       */
      public Builder setResponseJsonFormatValue(int value) {
        
        responseJsonFormat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.trinsic.services.JsonFormat response_json_format = 1;</code>
       * @return The responseJsonFormat.
       */
      @java.lang.Override
      public trinsic.services.CoreService.JsonFormat getResponseJsonFormat() {
        @SuppressWarnings("deprecation")
        trinsic.services.CoreService.JsonFormat result = trinsic.services.CoreService.JsonFormat.valueOf(responseJsonFormat_);
        return result == null ? trinsic.services.CoreService.JsonFormat.UNRECOGNIZED : result;
      }
      /**
       * <code>.trinsic.services.JsonFormat response_json_format = 1;</code>
       * @param value The responseJsonFormat to set.
       * @return This builder for chaining.
       */
      public Builder setResponseJsonFormat(trinsic.services.CoreService.JsonFormat value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        responseJsonFormat_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.trinsic.services.JsonFormat response_json_format = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseJsonFormat() {
        
        responseJsonFormat_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trinsic.services.RequestOptions)
    }

    // @@protoc_insertion_point(class_scope:trinsic.services.RequestOptions)
    private static final trinsic.services.CoreService.RequestOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new trinsic.services.CoreService.RequestOptions();
    }

    public static trinsic.services.CoreService.RequestOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestOptions>
        PARSER = new com.google.protobuf.AbstractParser<RequestOptions>() {
      @java.lang.Override
      public RequestOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public trinsic.services.CoreService.RequestOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JsonPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trinsic.services.JsonPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Struct json_struct = 1;</code>
     * @return Whether the jsonStruct field is set.
     */
    boolean hasJsonStruct();
    /**
     * <code>.google.protobuf.Struct json_struct = 1;</code>
     * @return The jsonStruct.
     */
    com.google.protobuf.Struct getJsonStruct();
    /**
     * <code>.google.protobuf.Struct json_struct = 1;</code>
     */
    com.google.protobuf.StructOrBuilder getJsonStructOrBuilder();

    /**
     * <code>string json_string = 2;</code>
     * @return Whether the jsonString field is set.
     */
    boolean hasJsonString();
    /**
     * <code>string json_string = 2;</code>
     * @return The jsonString.
     */
    java.lang.String getJsonString();
    /**
     * <code>string json_string = 2;</code>
     * @return The bytes for jsonString.
     */
    com.google.protobuf.ByteString
        getJsonStringBytes();

    /**
     * <code>bytes json_bytes = 3;</code>
     * @return Whether the jsonBytes field is set.
     */
    boolean hasJsonBytes();
    /**
     * <code>bytes json_bytes = 3;</code>
     * @return The jsonBytes.
     */
    com.google.protobuf.ByteString getJsonBytes();

    public trinsic.services.CoreService.JsonPayload.JsonCase getJsonCase();
  }
  /**
   * Protobuf type {@code trinsic.services.JsonPayload}
   */
  public static final class JsonPayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trinsic.services.JsonPayload)
      JsonPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JsonPayload.newBuilder() to construct.
    private JsonPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JsonPayload() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JsonPayload();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JsonPayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.Struct.Builder subBuilder = null;
              if (jsonCase_ == 1) {
                subBuilder = ((com.google.protobuf.Struct) json_).toBuilder();
              }
              json_ =
                  input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.google.protobuf.Struct) json_);
                json_ = subBuilder.buildPartial();
              }
              jsonCase_ = 1;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              jsonCase_ = 2;
              json_ = s;
              break;
            }
            case 26: {
              jsonCase_ = 3;
              json_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trinsic.services.CoreService.internal_static_trinsic_services_JsonPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trinsic.services.CoreService.internal_static_trinsic_services_JsonPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trinsic.services.CoreService.JsonPayload.class, trinsic.services.CoreService.JsonPayload.Builder.class);
    }

    private int jsonCase_ = 0;
    private java.lang.Object json_;
    public enum JsonCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      JSON_STRUCT(1),
      JSON_STRING(2),
      JSON_BYTES(3),
      JSON_NOT_SET(0);
      private final int value;
      private JsonCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static JsonCase valueOf(int value) {
        return forNumber(value);
      }

      public static JsonCase forNumber(int value) {
        switch (value) {
          case 1: return JSON_STRUCT;
          case 2: return JSON_STRING;
          case 3: return JSON_BYTES;
          case 0: return JSON_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public JsonCase
    getJsonCase() {
      return JsonCase.forNumber(
          jsonCase_);
    }

    public static final int JSON_STRUCT_FIELD_NUMBER = 1;
    /**
     * <code>.google.protobuf.Struct json_struct = 1;</code>
     * @return Whether the jsonStruct field is set.
     */
    @java.lang.Override
    public boolean hasJsonStruct() {
      return jsonCase_ == 1;
    }
    /**
     * <code>.google.protobuf.Struct json_struct = 1;</code>
     * @return The jsonStruct.
     */
    @java.lang.Override
    public com.google.protobuf.Struct getJsonStruct() {
      if (jsonCase_ == 1) {
         return (com.google.protobuf.Struct) json_;
      }
      return com.google.protobuf.Struct.getDefaultInstance();
    }
    /**
     * <code>.google.protobuf.Struct json_struct = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StructOrBuilder getJsonStructOrBuilder() {
      if (jsonCase_ == 1) {
         return (com.google.protobuf.Struct) json_;
      }
      return com.google.protobuf.Struct.getDefaultInstance();
    }

    public static final int JSON_STRING_FIELD_NUMBER = 2;
    /**
     * <code>string json_string = 2;</code>
     * @return Whether the jsonString field is set.
     */
    public boolean hasJsonString() {
      return jsonCase_ == 2;
    }
    /**
     * <code>string json_string = 2;</code>
     * @return The jsonString.
     */
    public java.lang.String getJsonString() {
      java.lang.Object ref = "";
      if (jsonCase_ == 2) {
        ref = json_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (jsonCase_ == 2) {
          json_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string json_string = 2;</code>
     * @return The bytes for jsonString.
     */
    public com.google.protobuf.ByteString
        getJsonStringBytes() {
      java.lang.Object ref = "";
      if (jsonCase_ == 2) {
        ref = json_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (jsonCase_ == 2) {
          json_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JSON_BYTES_FIELD_NUMBER = 3;
    /**
     * <code>bytes json_bytes = 3;</code>
     * @return Whether the jsonBytes field is set.
     */
    @java.lang.Override
    public boolean hasJsonBytes() {
      return jsonCase_ == 3;
    }
    /**
     * <code>bytes json_bytes = 3;</code>
     * @return The jsonBytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getJsonBytes() {
      if (jsonCase_ == 3) {
        return (com.google.protobuf.ByteString) json_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (jsonCase_ == 1) {
        output.writeMessage(1, (com.google.protobuf.Struct) json_);
      }
      if (jsonCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, json_);
      }
      if (jsonCase_ == 3) {
        output.writeBytes(
            3, (com.google.protobuf.ByteString) json_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (jsonCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.google.protobuf.Struct) json_);
      }
      if (jsonCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, json_);
      }
      if (jsonCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              3, (com.google.protobuf.ByteString) json_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof trinsic.services.CoreService.JsonPayload)) {
        return super.equals(obj);
      }
      trinsic.services.CoreService.JsonPayload other = (trinsic.services.CoreService.JsonPayload) obj;

      if (!getJsonCase().equals(other.getJsonCase())) return false;
      switch (jsonCase_) {
        case 1:
          if (!getJsonStruct()
              .equals(other.getJsonStruct())) return false;
          break;
        case 2:
          if (!getJsonString()
              .equals(other.getJsonString())) return false;
          break;
        case 3:
          if (!getJsonBytes()
              .equals(other.getJsonBytes())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (jsonCase_) {
        case 1:
          hash = (37 * hash) + JSON_STRUCT_FIELD_NUMBER;
          hash = (53 * hash) + getJsonStruct().hashCode();
          break;
        case 2:
          hash = (37 * hash) + JSON_STRING_FIELD_NUMBER;
          hash = (53 * hash) + getJsonString().hashCode();
          break;
        case 3:
          hash = (37 * hash) + JSON_BYTES_FIELD_NUMBER;
          hash = (53 * hash) + getJsonBytes().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static trinsic.services.CoreService.JsonPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trinsic.services.CoreService.JsonPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trinsic.services.CoreService.JsonPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trinsic.services.CoreService.JsonPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trinsic.services.CoreService.JsonPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trinsic.services.CoreService.JsonPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trinsic.services.CoreService.JsonPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trinsic.services.CoreService.JsonPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static trinsic.services.CoreService.JsonPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static trinsic.services.CoreService.JsonPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static trinsic.services.CoreService.JsonPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trinsic.services.CoreService.JsonPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(trinsic.services.CoreService.JsonPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trinsic.services.JsonPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trinsic.services.JsonPayload)
        trinsic.services.CoreService.JsonPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return trinsic.services.CoreService.internal_static_trinsic_services_JsonPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return trinsic.services.CoreService.internal_static_trinsic_services_JsonPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                trinsic.services.CoreService.JsonPayload.class, trinsic.services.CoreService.JsonPayload.Builder.class);
      }

      // Construct using trinsic.services.CoreService.JsonPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jsonCase_ = 0;
        json_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return trinsic.services.CoreService.internal_static_trinsic_services_JsonPayload_descriptor;
      }

      @java.lang.Override
      public trinsic.services.CoreService.JsonPayload getDefaultInstanceForType() {
        return trinsic.services.CoreService.JsonPayload.getDefaultInstance();
      }

      @java.lang.Override
      public trinsic.services.CoreService.JsonPayload build() {
        trinsic.services.CoreService.JsonPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public trinsic.services.CoreService.JsonPayload buildPartial() {
        trinsic.services.CoreService.JsonPayload result = new trinsic.services.CoreService.JsonPayload(this);
        if (jsonCase_ == 1) {
          if (jsonStructBuilder_ == null) {
            result.json_ = json_;
          } else {
            result.json_ = jsonStructBuilder_.build();
          }
        }
        if (jsonCase_ == 2) {
          result.json_ = json_;
        }
        if (jsonCase_ == 3) {
          result.json_ = json_;
        }
        result.jsonCase_ = jsonCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof trinsic.services.CoreService.JsonPayload) {
          return mergeFrom((trinsic.services.CoreService.JsonPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(trinsic.services.CoreService.JsonPayload other) {
        if (other == trinsic.services.CoreService.JsonPayload.getDefaultInstance()) return this;
        switch (other.getJsonCase()) {
          case JSON_STRUCT: {
            mergeJsonStruct(other.getJsonStruct());
            break;
          }
          case JSON_STRING: {
            jsonCase_ = 2;
            json_ = other.json_;
            onChanged();
            break;
          }
          case JSON_BYTES: {
            setJsonBytes(other.getJsonBytes());
            break;
          }
          case JSON_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        trinsic.services.CoreService.JsonPayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (trinsic.services.CoreService.JsonPayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int jsonCase_ = 0;
      private java.lang.Object json_;
      public JsonCase
          getJsonCase() {
        return JsonCase.forNumber(
            jsonCase_);
      }

      public Builder clearJson() {
        jsonCase_ = 0;
        json_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> jsonStructBuilder_;
      /**
       * <code>.google.protobuf.Struct json_struct = 1;</code>
       * @return Whether the jsonStruct field is set.
       */
      @java.lang.Override
      public boolean hasJsonStruct() {
        return jsonCase_ == 1;
      }
      /**
       * <code>.google.protobuf.Struct json_struct = 1;</code>
       * @return The jsonStruct.
       */
      @java.lang.Override
      public com.google.protobuf.Struct getJsonStruct() {
        if (jsonStructBuilder_ == null) {
          if (jsonCase_ == 1) {
            return (com.google.protobuf.Struct) json_;
          }
          return com.google.protobuf.Struct.getDefaultInstance();
        } else {
          if (jsonCase_ == 1) {
            return jsonStructBuilder_.getMessage();
          }
          return com.google.protobuf.Struct.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Struct json_struct = 1;</code>
       */
      public Builder setJsonStruct(com.google.protobuf.Struct value) {
        if (jsonStructBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          json_ = value;
          onChanged();
        } else {
          jsonStructBuilder_.setMessage(value);
        }
        jsonCase_ = 1;
        return this;
      }
      /**
       * <code>.google.protobuf.Struct json_struct = 1;</code>
       */
      public Builder setJsonStruct(
          com.google.protobuf.Struct.Builder builderForValue) {
        if (jsonStructBuilder_ == null) {
          json_ = builderForValue.build();
          onChanged();
        } else {
          jsonStructBuilder_.setMessage(builderForValue.build());
        }
        jsonCase_ = 1;
        return this;
      }
      /**
       * <code>.google.protobuf.Struct json_struct = 1;</code>
       */
      public Builder mergeJsonStruct(com.google.protobuf.Struct value) {
        if (jsonStructBuilder_ == null) {
          if (jsonCase_ == 1 &&
              json_ != com.google.protobuf.Struct.getDefaultInstance()) {
            json_ = com.google.protobuf.Struct.newBuilder((com.google.protobuf.Struct) json_)
                .mergeFrom(value).buildPartial();
          } else {
            json_ = value;
          }
          onChanged();
        } else {
          if (jsonCase_ == 1) {
            jsonStructBuilder_.mergeFrom(value);
          }
          jsonStructBuilder_.setMessage(value);
        }
        jsonCase_ = 1;
        return this;
      }
      /**
       * <code>.google.protobuf.Struct json_struct = 1;</code>
       */
      public Builder clearJsonStruct() {
        if (jsonStructBuilder_ == null) {
          if (jsonCase_ == 1) {
            jsonCase_ = 0;
            json_ = null;
            onChanged();
          }
        } else {
          if (jsonCase_ == 1) {
            jsonCase_ = 0;
            json_ = null;
          }
          jsonStructBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Struct json_struct = 1;</code>
       */
      public com.google.protobuf.Struct.Builder getJsonStructBuilder() {
        return getJsonStructFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Struct json_struct = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.StructOrBuilder getJsonStructOrBuilder() {
        if ((jsonCase_ == 1) && (jsonStructBuilder_ != null)) {
          return jsonStructBuilder_.getMessageOrBuilder();
        } else {
          if (jsonCase_ == 1) {
            return (com.google.protobuf.Struct) json_;
          }
          return com.google.protobuf.Struct.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Struct json_struct = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
          getJsonStructFieldBuilder() {
        if (jsonStructBuilder_ == null) {
          if (!(jsonCase_ == 1)) {
            json_ = com.google.protobuf.Struct.getDefaultInstance();
          }
          jsonStructBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                  (com.google.protobuf.Struct) json_,
                  getParentForChildren(),
                  isClean());
          json_ = null;
        }
        jsonCase_ = 1;
        onChanged();;
        return jsonStructBuilder_;
      }

      /**
       * <code>string json_string = 2;</code>
       * @return Whether the jsonString field is set.
       */
      @java.lang.Override
      public boolean hasJsonString() {
        return jsonCase_ == 2;
      }
      /**
       * <code>string json_string = 2;</code>
       * @return The jsonString.
       */
      @java.lang.Override
      public java.lang.String getJsonString() {
        java.lang.Object ref = "";
        if (jsonCase_ == 2) {
          ref = json_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (jsonCase_ == 2) {
            json_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string json_string = 2;</code>
       * @return The bytes for jsonString.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getJsonStringBytes() {
        java.lang.Object ref = "";
        if (jsonCase_ == 2) {
          ref = json_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (jsonCase_ == 2) {
            json_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string json_string = 2;</code>
       * @param value The jsonString to set.
       * @return This builder for chaining.
       */
      public Builder setJsonString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  jsonCase_ = 2;
        json_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string json_string = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearJsonString() {
        if (jsonCase_ == 2) {
          jsonCase_ = 0;
          json_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string json_string = 2;</code>
       * @param value The bytes for jsonString to set.
       * @return This builder for chaining.
       */
      public Builder setJsonStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        jsonCase_ = 2;
        json_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bytes json_bytes = 3;</code>
       * @return Whether the jsonBytes field is set.
       */
      public boolean hasJsonBytes() {
        return jsonCase_ == 3;
      }
      /**
       * <code>bytes json_bytes = 3;</code>
       * @return The jsonBytes.
       */
      public com.google.protobuf.ByteString getJsonBytes() {
        if (jsonCase_ == 3) {
          return (com.google.protobuf.ByteString) json_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <code>bytes json_bytes = 3;</code>
       * @param value The jsonBytes to set.
       * @return This builder for chaining.
       */
      public Builder setJsonBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  jsonCase_ = 3;
        json_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes json_bytes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearJsonBytes() {
        if (jsonCase_ == 3) {
          jsonCase_ = 0;
          json_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trinsic.services.JsonPayload)
    }

    // @@protoc_insertion_point(class_scope:trinsic.services.JsonPayload)
    private static final trinsic.services.CoreService.JsonPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new trinsic.services.CoreService.JsonPayload();
    }

    public static trinsic.services.CoreService.JsonPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JsonPayload>
        PARSER = new com.google.protobuf.AbstractParser<JsonPayload>() {
      @java.lang.Override
      public JsonPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JsonPayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JsonPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JsonPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public trinsic.services.CoreService.JsonPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trinsic_services_RequestOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trinsic_services_RequestOptions_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trinsic_services_JsonPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trinsic_services_JsonPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CoreService.proto\022\020trinsic.services\032\034g" +
      "oogle/protobuf/struct.proto\032\021pbmse/pbmse" +
      ".proto\"L\n\016RequestOptions\022:\n\024response_jso" +
      "n_format\030\001 \001(\0162\034.trinsic.services.JsonFo" +
      "rmat\"r\n\013JsonPayload\022.\n\013json_struct\030\001 \001(\013" +
      "2\027.google.protobuf.StructH\000\022\025\n\013json_stri" +
      "ng\030\002 \001(\tH\000\022\024\n\njson_bytes\030\003 \001(\014H\000B\006\n\004json" +
      "*\213\001\n\016ResponseStatus\022\013\n\007SUCCESS\020\000\022\030\n\024WALL" +
      "ET_ACCESS_DENIED\020\n\022\021\n\rWALLET_EXISTS\020\013\022\022\n" +
      "\016ITEM_NOT_FOUND\020\024\022\030\n\023SERIALIZATION_ERROR" +
      "\020\310\001\022\021\n\rUNKNOWN_ERROR\020d*2\n\nJsonFormat\022\014\n\010" +
      "Protobuf\020\000\022\n\n\006Binary\020\001\022\n\n\006String\020\0022E\n\006Co" +
      "mmon\022;\n\007Request\022\027.pbmse.EncryptedMessage" +
      "\032\027.pbmse.EncryptedMessageB-\n\020trinsic.ser" +
      "vicesZ\031github.com/trinsic-id/sdkb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          trinsic.services.Pbmse.getDescriptor(),
        });
    internal_static_trinsic_services_RequestOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trinsic_services_RequestOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trinsic_services_RequestOptions_descriptor,
        new java.lang.String[] { "ResponseJsonFormat", });
    internal_static_trinsic_services_JsonPayload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trinsic_services_JsonPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trinsic_services_JsonPayload_descriptor,
        new java.lang.String[] { "JsonStruct", "JsonString", "JsonBytes", "Json", });
    com.google.protobuf.StructProto.getDescriptor();
    trinsic.services.Pbmse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
