# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/provider/v1/access-management.proto

require 'google/protobuf'

require 'services/options/field-options_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("services/provider/v1/access-management.proto", :syntax => :proto3) do
    add_message "services.provider.v1.AddRoleAssignmentRequest" do
      optional :role, :string, 1
      oneof :account do
        optional :email, :string, 2
        optional :wallet_id, :string, 3
      end
    end
    add_message "services.provider.v1.AddRoleAssignmentResponse" do
    end
    add_message "services.provider.v1.RemoveRoleAssignmentRequest" do
      optional :role, :string, 1
      oneof :account do
        optional :email, :string, 2
        optional :wallet_id, :string, 3
      end
    end
    add_message "services.provider.v1.RemoveRoleAssignmentResponse" do
    end
    add_message "services.provider.v1.ListRoleAssignmentsRequest" do
      oneof :account do
        optional :email, :string, 2
        optional :wallet_id, :string, 3
      end
    end
    add_message "services.provider.v1.ListRoleAssignmentsResponse" do
      repeated :roles, :string, 1
    end
    add_message "services.provider.v1.ListAvailableRolesRequest" do
    end
    add_message "services.provider.v1.ListAvailableRolesResponse" do
      repeated :roles, :string, 1
    end
  end
end

module Services
  module Provider
    module V1
      AddRoleAssignmentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("services.provider.v1.AddRoleAssignmentRequest").msgclass
      AddRoleAssignmentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("services.provider.v1.AddRoleAssignmentResponse").msgclass
      RemoveRoleAssignmentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("services.provider.v1.RemoveRoleAssignmentRequest").msgclass
      RemoveRoleAssignmentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("services.provider.v1.RemoveRoleAssignmentResponse").msgclass
      ListRoleAssignmentsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("services.provider.v1.ListRoleAssignmentsRequest").msgclass
      ListRoleAssignmentsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("services.provider.v1.ListRoleAssignmentsResponse").msgclass
      ListAvailableRolesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("services.provider.v1.ListAvailableRolesRequest").msgclass
      ListAvailableRolesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("services.provider.v1.ListAvailableRolesResponse").msgclass
    end
  end
end
