// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/verifiable-credentials/templates/v1/templates.proto

package trinsic.services.verifiablecredentials.templates.v1;

public interface CreateVerificationTemplateResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:services.verifiablecredentials.templates.v1.CreateVerificationTemplateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.services.verifiablecredentials.templates.v1.VerificationTemplateData data = 1;</code>
   *
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.services.verifiablecredentials.templates.v1.VerificationTemplateData data = 1;</code>
   *
   * @return The data.
   */
  trinsic.services.verifiablecredentials.templates.v1.VerificationTemplateData getData();
  /**
   * <code>.services.verifiablecredentials.templates.v1.VerificationTemplateData data = 1;</code>
   */
  trinsic.services.verifiablecredentials.templates.v1.VerificationTemplateDataOrBuilder
      getDataOrBuilder();
}
