// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/verifiable-credentials/templates/v1/templates.proto

package trinsic.services.verifiablecredentials.templates.v1;

public interface ListVerificationTemplatesResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:services.verifiablecredentials.templates.v1.ListVerificationTemplatesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Templates found by query
   * </pre>
   *
   * <code>
   * repeated .services.verifiablecredentials.templates.v1.VerificationTemplateData templates = 1;
   * </code>
   */
  java.util.List<trinsic.services.verifiablecredentials.templates.v1.VerificationTemplateData>
      getTemplatesList();
  /**
   *
   *
   * <pre>
   * Templates found by query
   * </pre>
   *
   * <code>
   * repeated .services.verifiablecredentials.templates.v1.VerificationTemplateData templates = 1;
   * </code>
   */
  trinsic.services.verifiablecredentials.templates.v1.VerificationTemplateData getTemplates(
      int index);
  /**
   *
   *
   * <pre>
   * Templates found by query
   * </pre>
   *
   * <code>
   * repeated .services.verifiablecredentials.templates.v1.VerificationTemplateData templates = 1;
   * </code>
   */
  int getTemplatesCount();
  /**
   *
   *
   * <pre>
   * Templates found by query
   * </pre>
   *
   * <code>
   * repeated .services.verifiablecredentials.templates.v1.VerificationTemplateData templates = 1;
   * </code>
   */
  java.util.List<
          ? extends
              trinsic.services.verifiablecredentials.templates.v1.VerificationTemplateDataOrBuilder>
      getTemplatesOrBuilderList();
  /**
   *
   *
   * <pre>
   * Templates found by query
   * </pre>
   *
   * <code>
   * repeated .services.verifiablecredentials.templates.v1.VerificationTemplateData templates = 1;
   * </code>
   */
  trinsic.services.verifiablecredentials.templates.v1.VerificationTemplateDataOrBuilder
      getTemplatesOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * Whether more results are available for this query via `continuation_token`
   * </pre>
   *
   * <code>bool has_more_results = 2;</code>
   *
   * @return The hasMoreResults.
   */
  boolean getHasMoreResults();

  /**
   *
   *
   * <pre>
   * Token to fetch next set of results via `ListVerificationTemplatesRequest`
   * </pre>
   *
   * <code>string continuation_token = 3;</code>
   *
   * @return The continuationToken.
   */
  java.lang.String getContinuationToken();
  /**
   *
   *
   * <pre>
   * Token to fetch next set of results via `ListVerificationTemplatesRequest`
   * </pre>
   *
   * <code>string continuation_token = 3;</code>
   *
   * @return The bytes for continuationToken.
   */
  com.google.protobuf.ByteString getContinuationTokenBytes();
}
