// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/provider/v1/provider.proto

package trinsic.services.provider.v1;

public interface EcosystemDisplayDetailsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:services.provider.v1.EcosystemDisplayDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string logo_url = 3;</code>
   *
   * @return The logoUrl.
   */
  java.lang.String getLogoUrl();
  /**
   * <code>string logo_url = 3;</code>
   *
   * @return The bytes for logoUrl.
   */
  com.google.protobuf.ByteString getLogoUrlBytes();

  /**
   * <code>string color = 4;</code>
   *
   * @return The color.
   */
  java.lang.String getColor();
  /**
   * <code>string color = 4;</code>
   *
   * @return The bytes for color.
   */
  com.google.protobuf.ByteString getColorBytes();
}
