// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/provider/v1/provider.proto

package trinsic.services.provider.v1;

public interface IndyOptionsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:services.provider.v1.IndyOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * SOV network on which DID should be published
   * </pre>
   *
   * <code>.services.provider.v1.IndyOptions.IndyNetwork network = 1;</code>
   *
   * @return The enum numeric value on the wire for network.
   */
  int getNetworkValue();
  /**
   *
   *
   * <pre>
   * SOV network on which DID should be published
   * </pre>
   *
   * <code>.services.provider.v1.IndyOptions.IndyNetwork network = 1;</code>
   *
   * @return The network.
   */
  trinsic.services.provider.v1.IndyOptions.IndyNetwork getNetwork();
}
