// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/provider/v1/provider.proto

package trinsic.services.provider.v1;

public interface RefreshDomainVerificationStatusRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:services.provider.v1.RefreshDomainVerificationStatusRequest)
    com.google.protobuf.MessageOrBuilder {}
