// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/file-management/v1/file-management.proto

package trinsic.services.filemanagement.v1;

/**
 *
 *
 * <pre>
 * Represents aggregate statistics of all files uploaded by a single issuer
 * </pre>
 *
 * Protobuf type {@code services.filemanagement.v1.StorageStats}
 */
public final class StorageStats extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:services.filemanagement.v1.StorageStats)
    StorageStatsOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use StorageStats.newBuilder() to construct.
  private StorageStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private StorageStats() {}

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new StorageStats();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return trinsic.services.filemanagement.v1.FileManagementOuterClass
        .internal_static_services_filemanagement_v1_StorageStats_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return trinsic.services.filemanagement.v1.FileManagementOuterClass
        .internal_static_services_filemanagement_v1_StorageStats_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            trinsic.services.filemanagement.v1.StorageStats.class,
            trinsic.services.filemanagement.v1.StorageStats.Builder.class);
  }

  public static final int NUM_FILES_FIELD_NUMBER = 1;
  private int numFiles_;
  /**
   *
   *
   * <pre>
   * Number of files uploaded by this account
   * </pre>
   *
   * <code>uint32 num_files = 1;</code>
   *
   * @return The numFiles.
   */
  @java.lang.Override
  public int getNumFiles() {
    return numFiles_;
  }

  public static final int TOTAL_SIZE_FIELD_NUMBER = 2;
  private long totalSize_;
  /**
   *
   *
   * <pre>
   * Sum total size of all files, in bytes
   * </pre>
   *
   * <code>uint64 total_size = 2;</code>
   *
   * @return The totalSize.
   */
  @java.lang.Override
  public long getTotalSize() {
    return totalSize_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (numFiles_ != 0) {
      output.writeUInt32(1, numFiles_);
    }
    if (totalSize_ != 0L) {
      output.writeUInt64(2, totalSize_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numFiles_ != 0) {
      size += com.google.protobuf.CodedOutputStream.computeUInt32Size(1, numFiles_);
    }
    if (totalSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeUInt64Size(2, totalSize_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof trinsic.services.filemanagement.v1.StorageStats)) {
      return super.equals(obj);
    }
    trinsic.services.filemanagement.v1.StorageStats other =
        (trinsic.services.filemanagement.v1.StorageStats) obj;

    if (getNumFiles() != other.getNumFiles()) return false;
    if (getTotalSize() != other.getTotalSize()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUM_FILES_FIELD_NUMBER;
    hash = (53 * hash) + getNumFiles();
    hash = (37 * hash) + TOTAL_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTotalSize());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static trinsic.services.filemanagement.v1.StorageStats parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static trinsic.services.filemanagement.v1.StorageStats parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static trinsic.services.filemanagement.v1.StorageStats parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static trinsic.services.filemanagement.v1.StorageStats parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static trinsic.services.filemanagement.v1.StorageStats parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static trinsic.services.filemanagement.v1.StorageStats parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static trinsic.services.filemanagement.v1.StorageStats parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static trinsic.services.filemanagement.v1.StorageStats parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static trinsic.services.filemanagement.v1.StorageStats parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static trinsic.services.filemanagement.v1.StorageStats parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static trinsic.services.filemanagement.v1.StorageStats parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static trinsic.services.filemanagement.v1.StorageStats parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(trinsic.services.filemanagement.v1.StorageStats prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Represents aggregate statistics of all files uploaded by a single issuer
   * </pre>
   *
   * Protobuf type {@code services.filemanagement.v1.StorageStats}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:services.filemanagement.v1.StorageStats)
      trinsic.services.filemanagement.v1.StorageStatsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return trinsic.services.filemanagement.v1.FileManagementOuterClass
          .internal_static_services_filemanagement_v1_StorageStats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trinsic.services.filemanagement.v1.FileManagementOuterClass
          .internal_static_services_filemanagement_v1_StorageStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trinsic.services.filemanagement.v1.StorageStats.class,
              trinsic.services.filemanagement.v1.StorageStats.Builder.class);
    }

    // Construct using trinsic.services.filemanagement.v1.StorageStats.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      numFiles_ = 0;

      totalSize_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return trinsic.services.filemanagement.v1.FileManagementOuterClass
          .internal_static_services_filemanagement_v1_StorageStats_descriptor;
    }

    @java.lang.Override
    public trinsic.services.filemanagement.v1.StorageStats getDefaultInstanceForType() {
      return trinsic.services.filemanagement.v1.StorageStats.getDefaultInstance();
    }

    @java.lang.Override
    public trinsic.services.filemanagement.v1.StorageStats build() {
      trinsic.services.filemanagement.v1.StorageStats result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public trinsic.services.filemanagement.v1.StorageStats buildPartial() {
      trinsic.services.filemanagement.v1.StorageStats result =
          new trinsic.services.filemanagement.v1.StorageStats(this);
      result.numFiles_ = numFiles_;
      result.totalSize_ = totalSize_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof trinsic.services.filemanagement.v1.StorageStats) {
        return mergeFrom((trinsic.services.filemanagement.v1.StorageStats) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(trinsic.services.filemanagement.v1.StorageStats other) {
      if (other == trinsic.services.filemanagement.v1.StorageStats.getDefaultInstance())
        return this;
      if (other.getNumFiles() != 0) {
        setNumFiles(other.getNumFiles());
      }
      if (other.getTotalSize() != 0L) {
        setTotalSize(other.getTotalSize());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8:
              {
                numFiles_ = input.readUInt32();

                break;
              } // case 8
            case 16:
              {
                totalSize_ = input.readUInt64();

                break;
              } // case 16
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int numFiles_;
    /**
     *
     *
     * <pre>
     * Number of files uploaded by this account
     * </pre>
     *
     * <code>uint32 num_files = 1;</code>
     *
     * @return The numFiles.
     */
    @java.lang.Override
    public int getNumFiles() {
      return numFiles_;
    }
    /**
     *
     *
     * <pre>
     * Number of files uploaded by this account
     * </pre>
     *
     * <code>uint32 num_files = 1;</code>
     *
     * @param value The numFiles to set.
     * @return This builder for chaining.
     */
    public Builder setNumFiles(int value) {

      numFiles_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Number of files uploaded by this account
     * </pre>
     *
     * <code>uint32 num_files = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearNumFiles() {

      numFiles_ = 0;
      onChanged();
      return this;
    }

    private long totalSize_;
    /**
     *
     *
     * <pre>
     * Sum total size of all files, in bytes
     * </pre>
     *
     * <code>uint64 total_size = 2;</code>
     *
     * @return The totalSize.
     */
    @java.lang.Override
    public long getTotalSize() {
      return totalSize_;
    }
    /**
     *
     *
     * <pre>
     * Sum total size of all files, in bytes
     * </pre>
     *
     * <code>uint64 total_size = 2;</code>
     *
     * @param value The totalSize to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSize(long value) {

      totalSize_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Sum total size of all files, in bytes
     * </pre>
     *
     * <code>uint64 total_size = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearTotalSize() {

      totalSize_ = 0L;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:services.filemanagement.v1.StorageStats)
  }

  // @@protoc_insertion_point(class_scope:services.filemanagement.v1.StorageStats)
  private static final trinsic.services.filemanagement.v1.StorageStats DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new trinsic.services.filemanagement.v1.StorageStats();
  }

  public static trinsic.services.filemanagement.v1.StorageStats getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StorageStats> PARSER =
      new com.google.protobuf.AbstractParser<StorageStats>() {
        @java.lang.Override
        public StorageStats parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<StorageStats> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StorageStats> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public trinsic.services.filemanagement.v1.StorageStats getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
