// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/connect/v1/connect.proto

package trinsic.services.connect.v1;

public interface GetSessionResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:services.connect.v1.GetSessionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The IDVSession
   * </pre>
   *
   * <code>.services.connect.v1.IDVSession session = 1;</code>
   *
   * @return Whether the session field is set.
   */
  boolean hasSession();
  /**
   *
   *
   * <pre>
   * The IDVSession
   * </pre>
   *
   * <code>.services.connect.v1.IDVSession session = 1;</code>
   *
   * @return The session.
   */
  trinsic.services.connect.v1.IDVSession getSession();
  /**
   *
   *
   * <pre>
   * The IDVSession
   * </pre>
   *
   * <code>.services.connect.v1.IDVSession session = 1;</code>
   */
  trinsic.services.connect.v1.IDVSessionOrBuilder getSessionOrBuilder();
}
