// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/account/v1/account.proto

package trinsic.services.account.v1;

/**
 *
 *
 * <pre>
 * Response to `LoginConfirmRequest`
 * </pre>
 *
 * Protobuf type {@code services.account.v1.LoginConfirmResponse}
 */
public final class LoginConfirmResponse extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:services.account.v1.LoginConfirmResponse)
    LoginConfirmResponseOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use LoginConfirmResponse.newBuilder() to construct.
  private LoginConfirmResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private LoginConfirmResponse() {}

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new LoginConfirmResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return trinsic.services.account.v1.AccountOuterClass
        .internal_static_services_account_v1_LoginConfirmResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return trinsic.services.account.v1.AccountOuterClass
        .internal_static_services_account_v1_LoginConfirmResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            trinsic.services.account.v1.LoginConfirmResponse.class,
            trinsic.services.account.v1.LoginConfirmResponse.Builder.class);
  }

  public static final int PROFILE_FIELD_NUMBER = 1;
  private trinsic.services.account.v1.AccountProfile profile_;
  /**
   *
   *
   * <pre>
   * Profile response; must be unprotected using unhashed confirmation code.
   * Our SDKs will handle this process for you, and return to you an authentication token string.
   * </pre>
   *
   * <code>.services.account.v1.AccountProfile profile = 1;</code>
   *
   * @return Whether the profile field is set.
   */
  @java.lang.Override
  public boolean hasProfile() {
    return profile_ != null;
  }
  /**
   *
   *
   * <pre>
   * Profile response; must be unprotected using unhashed confirmation code.
   * Our SDKs will handle this process for you, and return to you an authentication token string.
   * </pre>
   *
   * <code>.services.account.v1.AccountProfile profile = 1;</code>
   *
   * @return The profile.
   */
  @java.lang.Override
  public trinsic.services.account.v1.AccountProfile getProfile() {
    return profile_ == null
        ? trinsic.services.account.v1.AccountProfile.getDefaultInstance()
        : profile_;
  }
  /**
   *
   *
   * <pre>
   * Profile response; must be unprotected using unhashed confirmation code.
   * Our SDKs will handle this process for you, and return to you an authentication token string.
   * </pre>
   *
   * <code>.services.account.v1.AccountProfile profile = 1;</code>
   */
  @java.lang.Override
  public trinsic.services.account.v1.AccountProfileOrBuilder getProfileOrBuilder() {
    return getProfile();
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (profile_ != null) {
      output.writeMessage(1, getProfile());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (profile_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getProfile());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof trinsic.services.account.v1.LoginConfirmResponse)) {
      return super.equals(obj);
    }
    trinsic.services.account.v1.LoginConfirmResponse other =
        (trinsic.services.account.v1.LoginConfirmResponse) obj;

    if (hasProfile() != other.hasProfile()) return false;
    if (hasProfile()) {
      if (!getProfile().equals(other.getProfile())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProfile()) {
      hash = (37 * hash) + PROFILE_FIELD_NUMBER;
      hash = (53 * hash) + getProfile().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static trinsic.services.account.v1.LoginConfirmResponse parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static trinsic.services.account.v1.LoginConfirmResponse parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static trinsic.services.account.v1.LoginConfirmResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static trinsic.services.account.v1.LoginConfirmResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static trinsic.services.account.v1.LoginConfirmResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static trinsic.services.account.v1.LoginConfirmResponse parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static trinsic.services.account.v1.LoginConfirmResponse parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static trinsic.services.account.v1.LoginConfirmResponse parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static trinsic.services.account.v1.LoginConfirmResponse parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static trinsic.services.account.v1.LoginConfirmResponse parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static trinsic.services.account.v1.LoginConfirmResponse parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static trinsic.services.account.v1.LoginConfirmResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(trinsic.services.account.v1.LoginConfirmResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Response to `LoginConfirmRequest`
   * </pre>
   *
   * Protobuf type {@code services.account.v1.LoginConfirmResponse}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:services.account.v1.LoginConfirmResponse)
      trinsic.services.account.v1.LoginConfirmResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return trinsic.services.account.v1.AccountOuterClass
          .internal_static_services_account_v1_LoginConfirmResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trinsic.services.account.v1.AccountOuterClass
          .internal_static_services_account_v1_LoginConfirmResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trinsic.services.account.v1.LoginConfirmResponse.class,
              trinsic.services.account.v1.LoginConfirmResponse.Builder.class);
    }

    // Construct using trinsic.services.account.v1.LoginConfirmResponse.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (profileBuilder_ == null) {
        profile_ = null;
      } else {
        profile_ = null;
        profileBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return trinsic.services.account.v1.AccountOuterClass
          .internal_static_services_account_v1_LoginConfirmResponse_descriptor;
    }

    @java.lang.Override
    public trinsic.services.account.v1.LoginConfirmResponse getDefaultInstanceForType() {
      return trinsic.services.account.v1.LoginConfirmResponse.getDefaultInstance();
    }

    @java.lang.Override
    public trinsic.services.account.v1.LoginConfirmResponse build() {
      trinsic.services.account.v1.LoginConfirmResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public trinsic.services.account.v1.LoginConfirmResponse buildPartial() {
      trinsic.services.account.v1.LoginConfirmResponse result =
          new trinsic.services.account.v1.LoginConfirmResponse(this);
      if (profileBuilder_ == null) {
        result.profile_ = profile_;
      } else {
        result.profile_ = profileBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof trinsic.services.account.v1.LoginConfirmResponse) {
        return mergeFrom((trinsic.services.account.v1.LoginConfirmResponse) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(trinsic.services.account.v1.LoginConfirmResponse other) {
      if (other == trinsic.services.account.v1.LoginConfirmResponse.getDefaultInstance())
        return this;
      if (other.hasProfile()) {
        mergeProfile(other.getProfile());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                input.readMessage(getProfileFieldBuilder().getBuilder(), extensionRegistry);

                break;
              } // case 10
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private trinsic.services.account.v1.AccountProfile profile_;
    private com.google.protobuf.SingleFieldBuilderV3<
            trinsic.services.account.v1.AccountProfile,
            trinsic.services.account.v1.AccountProfile.Builder,
            trinsic.services.account.v1.AccountProfileOrBuilder>
        profileBuilder_;
    /**
     *
     *
     * <pre>
     * Profile response; must be unprotected using unhashed confirmation code.
     * Our SDKs will handle this process for you, and return to you an authentication token string.
     * </pre>
     *
     * <code>.services.account.v1.AccountProfile profile = 1;</code>
     *
     * @return Whether the profile field is set.
     */
    public boolean hasProfile() {
      return profileBuilder_ != null || profile_ != null;
    }
    /**
     *
     *
     * <pre>
     * Profile response; must be unprotected using unhashed confirmation code.
     * Our SDKs will handle this process for you, and return to you an authentication token string.
     * </pre>
     *
     * <code>.services.account.v1.AccountProfile profile = 1;</code>
     *
     * @return The profile.
     */
    public trinsic.services.account.v1.AccountProfile getProfile() {
      if (profileBuilder_ == null) {
        return profile_ == null
            ? trinsic.services.account.v1.AccountProfile.getDefaultInstance()
            : profile_;
      } else {
        return profileBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Profile response; must be unprotected using unhashed confirmation code.
     * Our SDKs will handle this process for you, and return to you an authentication token string.
     * </pre>
     *
     * <code>.services.account.v1.AccountProfile profile = 1;</code>
     */
    public Builder setProfile(trinsic.services.account.v1.AccountProfile value) {
      if (profileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        profile_ = value;
        onChanged();
      } else {
        profileBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Profile response; must be unprotected using unhashed confirmation code.
     * Our SDKs will handle this process for you, and return to you an authentication token string.
     * </pre>
     *
     * <code>.services.account.v1.AccountProfile profile = 1;</code>
     */
    public Builder setProfile(trinsic.services.account.v1.AccountProfile.Builder builderForValue) {
      if (profileBuilder_ == null) {
        profile_ = builderForValue.build();
        onChanged();
      } else {
        profileBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Profile response; must be unprotected using unhashed confirmation code.
     * Our SDKs will handle this process for you, and return to you an authentication token string.
     * </pre>
     *
     * <code>.services.account.v1.AccountProfile profile = 1;</code>
     */
    public Builder mergeProfile(trinsic.services.account.v1.AccountProfile value) {
      if (profileBuilder_ == null) {
        if (profile_ != null) {
          profile_ =
              trinsic.services.account.v1.AccountProfile.newBuilder(profile_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          profile_ = value;
        }
        onChanged();
      } else {
        profileBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Profile response; must be unprotected using unhashed confirmation code.
     * Our SDKs will handle this process for you, and return to you an authentication token string.
     * </pre>
     *
     * <code>.services.account.v1.AccountProfile profile = 1;</code>
     */
    public Builder clearProfile() {
      if (profileBuilder_ == null) {
        profile_ = null;
        onChanged();
      } else {
        profile_ = null;
        profileBuilder_ = null;
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Profile response; must be unprotected using unhashed confirmation code.
     * Our SDKs will handle this process for you, and return to you an authentication token string.
     * </pre>
     *
     * <code>.services.account.v1.AccountProfile profile = 1;</code>
     */
    public trinsic.services.account.v1.AccountProfile.Builder getProfileBuilder() {

      onChanged();
      return getProfileFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Profile response; must be unprotected using unhashed confirmation code.
     * Our SDKs will handle this process for you, and return to you an authentication token string.
     * </pre>
     *
     * <code>.services.account.v1.AccountProfile profile = 1;</code>
     */
    public trinsic.services.account.v1.AccountProfileOrBuilder getProfileOrBuilder() {
      if (profileBuilder_ != null) {
        return profileBuilder_.getMessageOrBuilder();
      } else {
        return profile_ == null
            ? trinsic.services.account.v1.AccountProfile.getDefaultInstance()
            : profile_;
      }
    }
    /**
     *
     *
     * <pre>
     * Profile response; must be unprotected using unhashed confirmation code.
     * Our SDKs will handle this process for you, and return to you an authentication token string.
     * </pre>
     *
     * <code>.services.account.v1.AccountProfile profile = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            trinsic.services.account.v1.AccountProfile,
            trinsic.services.account.v1.AccountProfile.Builder,
            trinsic.services.account.v1.AccountProfileOrBuilder>
        getProfileFieldBuilder() {
      if (profileBuilder_ == null) {
        profileBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                trinsic.services.account.v1.AccountProfile,
                trinsic.services.account.v1.AccountProfile.Builder,
                trinsic.services.account.v1.AccountProfileOrBuilder>(
                getProfile(), getParentForChildren(), isClean());
        profile_ = null;
      }
      return profileBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:services.account.v1.LoginConfirmResponse)
  }

  // @@protoc_insertion_point(class_scope:services.account.v1.LoginConfirmResponse)
  private static final trinsic.services.account.v1.LoginConfirmResponse DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new trinsic.services.account.v1.LoginConfirmResponse();
  }

  public static trinsic.services.account.v1.LoginConfirmResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoginConfirmResponse> PARSER =
      new com.google.protobuf.AbstractParser<LoginConfirmResponse>() {
        @java.lang.Override
        public LoginConfirmResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<LoginConfirmResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoginConfirmResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public trinsic.services.account.v1.LoginConfirmResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
