/*
 * Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Trinsic.Connect.Model;

/// <summary>
/// Defines VerificationType
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum VerificationType
{
    /// <summary>
    /// Enum GovernmentId for value: GovernmentId
    /// </summary>
    [EnumMember(Value = "GovernmentId")]
    GovernmentId = 1
}
