# BEGIN Doc Code generated by protoc-gen-trinsic. DO NOT EDIT.
# target: /home/runner/work/sdk/sdk/python/samples/credentialtemplates_service_examples.py

# createCredentialTemplatesService
# }

# credentialTemplatesCreate() {
# }

# credentialTemplatesGet() {
# }

# credentialTemplatesUpdate() {
# }

# credentialTemplatesList() {
# }

# credentialTemplatesSearch() {
# }

# credentialTemplatesDelete() {
# }

# END Doc Code generated by protoc-gen-trinsic. DO NOT EDIT.
