/*
 * Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Xunit;

namespace Trinsic.Connect.Test.Model;

/// <summary>
///  Class for testing CanReuseCredentialResponse
/// </summary>
/// <remarks>
/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
/// Please update the test case below to test the model.
/// </remarks>
public class CanReuseCredentialResponseTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for CanReuseCredentialResponse
    //private CanReuseCredentialResponse instance;

    public CanReuseCredentialResponseTests()
    {
        // TODO uncomment below to create an instance of CanReuseCredentialResponse
        //instance = new CanReuseCredentialResponse();
    }

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of CanReuseCredentialResponse
    /// </summary>
    [Fact]
    public void CanReuseCredentialResponseInstanceTest()
    {
        // TODO uncomment below to test "IsType" CanReuseCredentialResponse
        //Assert.IsType<CanReuseCredentialResponse>(instance);
    }

    /// <summary>
    /// Test the property 'HasValidCredential'
    /// </summary>
    [Fact]
    public void HasValidCredentialTest()
    {
        // TODO unit test for the property 'HasValidCredential'
    }
}
