/*
 * Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Trinsic.Connect.Model;
using Trinsic.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Trinsic.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing CreateSessionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateSessionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateSessionResponse
        //private CreateSessionResponse instance;

        public CreateSessionResponseTests()
        {
            // TODO uncomment below to create an instance of CreateSessionResponse
            //instance = new CreateSessionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateSessionResponse
        /// </summary>
        [Fact]
        public void CreateSessionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateSessionResponse
            //Assert.IsType<CreateSessionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Session'
        /// </summary>
        [Fact]
        public void SessionTest()
        {
            // TODO unit test for the property 'Session'
        }
    }
}
