import ServiceBase from "./ServiceBase";
import {
    AccountProfile,
    AddWebhookRequest, AddWebhookResponse,
    CreateEcosystemRequest,
    CreateEcosystemResponse, DeleteWebhookRequest, DeleteWebhookResponse,
    EcosystemInfoRequest,
    EcosystemInfoResponse,
    GenerateTokenRequest,
    GenerateTokenResponse, GetAuthorizationsRequest, GetAuthorizationsResponse,
    GetEventTokenRequest,
    GetEventTokenResponse,
    GetOberonKeyRequest,
    GetOberonKeyResponse, GrantAuthorizationRequest, GrantAuthorizationResponse,
    InvitationStatusRequest,
    InvitationStatusResponse,
    InviteRequest,
    InviteResponse,
    ProviderDefinition, RevokeAuthorizationRequest, RevokeAuthorizationResponse,
    ServiceOptions,
    UpdateEcosystemRequest,
    UpdateEcosystemResponse,
} from "./proto";

import type { Client as BrowserClient } from "nice-grpc-web";
import base64url from "base64url";

export class ProviderService extends ServiceBase {
  client: BrowserClient<typeof ProviderDefinition>;

  constructor(options?: ServiceOptions) {
    super(options);

    this.client = this.createClient(ProviderDefinition);
  }

  public async createEcosystem(
    request: CreateEcosystemRequest
  ): Promise<CreateEcosystemResponse> {
    const response = request.name?.trim() || request.details?.email?.trim()
      ? await this.client.createEcosystem(request, {
        metadata: await this.buildMetadata(
          CreateEcosystemRequest.encode(request).finish()
        ),
      })
      : await this.client.createEcosystem(request);

      const authToken = base64url(
          Buffer.from(AccountProfile.encode(response.profile!).finish())
      );
      this.options.authToken = authToken;
      return response;
  }
// BEGIN Code generated by protoc-gen-trinsic. DO NOT EDIT.
// target: ..\sdk\web\src\providerService.ts

  public async updateEcosystem(
    request: UpdateEcosystemRequest
  ): Promise<UpdateEcosystemResponse> {
    return await this.client.updateEcosystem(request, {
      metadata: await this.buildMetadata(UpdateEcosystemRequest.encode(request).finish())
    });
  }
  public async grantAuthorization(
    request: GrantAuthorizationRequest
  ): Promise<GrantAuthorizationResponse> {
    return await this.client.grantAuthorization(request, {
      metadata: await this.buildMetadata(GrantAuthorizationRequest.encode(request).finish())
    });
  }
  public async revokeAuthorization(
    request: RevokeAuthorizationRequest
  ): Promise<RevokeAuthorizationResponse> {
    return await this.client.revokeAuthorization(request, {
      metadata: await this.buildMetadata(RevokeAuthorizationRequest.encode(request).finish())
    });
  }
  public async getAuthorizations(
    request: GetAuthorizationsRequest
  ): Promise<GetAuthorizationsResponse> {
    return await this.client.getAuthorizations(request, {
      metadata: await this.buildMetadata(GetAuthorizationsRequest.encode(request).finish())
    });
  }
  public async addWebhook(
    request: AddWebhookRequest
  ): Promise<AddWebhookResponse> {
    return await this.client.addWebhook(request, {
      metadata: await this.buildMetadata(AddWebhookRequest.encode(request).finish())
    });
  }
  public async deleteWebhook(
    request: DeleteWebhookRequest
  ): Promise<DeleteWebhookResponse> {
    return await this.client.deleteWebhook(request, {
      metadata: await this.buildMetadata(DeleteWebhookRequest.encode(request).finish())
    });
  }
  public async ecosystemInfo(
    request: EcosystemInfoRequest
  ): Promise<EcosystemInfoResponse> {
    return await this.client.ecosystemInfo(request, {
      metadata: await this.buildMetadata(EcosystemInfoRequest.encode(request).finish())
    });
  }
  public async generateToken(
    request: GenerateTokenRequest
  ): Promise<GenerateTokenResponse> {
    return await this.client.generateToken(request, {
      metadata: await this.buildMetadata(GenerateTokenRequest.encode(request).finish())
    });
  }
  public async invite(
    request: InviteRequest
  ): Promise<InviteResponse> {
    return await this.client.invite(request, {
      metadata: await this.buildMetadata(InviteRequest.encode(request).finish())
    });
  }
  public async invitationStatus(
    request: InvitationStatusRequest
  ): Promise<InvitationStatusResponse> {
    return await this.client.invitationStatus(request, {
      metadata: await this.buildMetadata(InvitationStatusRequest.encode(request).finish())
    });
  }
  public async getOberonKey(
    request: GetOberonKeyRequest
  ): Promise<GetOberonKeyResponse> {
    return this.client.getOberonKey(request, {
      metadata: await this.buildMetadata()
    });
  }
  public async getEventToken(
    request: GetEventTokenRequest
  ): Promise<GetEventTokenResponse> {
    return await this.client.getEventToken(request, {
      metadata: await this.buildMetadata(GetEventTokenRequest.encode(request).finish())
    });
  }
// END Code generated by protoc-gen-trinsic. DO NOT EDIT.
}
