// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/verifiable-credentials/v1/verifiable-credentials.proto

package trinsic.services.verifiablecredentials.v1;

public interface IssueFromTemplateResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:services.verifiablecredentials.v1.IssueFromTemplateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Verifiable Credential document, in JSON-LD form,
   * constructed from the specified template and values; signed
   * with public key tied to caller of `IssueFromTemplateRequest`
   * </pre>
   *
   * <code>string document_json = 1;</code>
   *
   * @return The documentJson.
   */
  java.lang.String getDocumentJson();
  /**
   *
   *
   * <pre>
   * Verifiable Credential document, in JSON-LD form,
   * constructed from the specified template and values; signed
   * with public key tied to caller of `IssueFromTemplateRequest`
   * </pre>
   *
   * <code>string document_json = 1;</code>
   *
   * @return The bytes for documentJson.
   */
  com.google.protobuf.ByteString getDocumentJsonBytes();
}
