/* tslint:disable */
/* eslint-disable */
/**
 * Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VerificationState = {
    VerificationPending: 'VerificationPending',
    VerificationSuccess: 'VerificationSuccess',
    VerificationFailed: 'VerificationFailed'
} as const;
export type VerificationState = typeof VerificationState[keyof typeof VerificationState];


export function instanceOfVerificationState(value: any): boolean {
    for (const key in VerificationState) {
        if (Object.prototype.hasOwnProperty.call(VerificationState, key)) {
            if ((VerificationState as Record<string, VerificationState>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VerificationStateFromJSON(json: any): VerificationState {
    return VerificationStateFromJSONTyped(json, false);
}

export function VerificationStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationState {
    return json as VerificationState;
}

export function VerificationStateToJSON(value?: VerificationState | null): any {
    return value as any;
}

